## Working with Missing Data in Pandas

In [2]:
import numpy as np
import pandas as pd

from pandas import DataFrame

### Filling missing values using fillna(), replace() and interpolate()

In [3]:
data = {'name': ['steve','john','richard','sarah','randy'
                 ,'micheal','julie']
        ,'age': [20,21,33,23,42,38,22]         
        ,'gender':['male','male','male','female','male'
                 ,'male','female']
        ,'rank':[2,1,3,5,4,7,6]         
                 }

In [4]:
ranking_df = DataFrame(data)

In [5]:
ranking_df

      name  age  gender  rank
0    steve   20    male     2
1     john   21    male     1
2  richard   33    male     3
3    sarah   23  female     5
4    randy   42    male     4
5  micheal   38    male     7
6    julie   22  female     6

In [6]:
ranking_df.iloc[2:5,1] = np.nan

In [7]:
ranking_df.iloc[3:6,3] = np.nan

In [8]:
ranking_df

      name   age  gender  rank
0    steve  20.0    male   2.0
1     john  21.0    male   1.0
2  richard   NaN    male   3.0
3    sarah   NaN  female   NaN
4    randy   NaN    male   NaN
5  micheal  38.0    male   NaN
6    julie  22.0  female   6.0

In [9]:
ranking_df.isnull().sum()

name      0
age       3
gender    0
rank      3
dtype: int64

In [12]:
ranking_df.notnull().sum()

name      7
age       4
gender    7
rank      4
dtype: int64

In [13]:
bool_series = pd.isnull(ranking_df['age'])
ranking_df[bool_series]

      name  age  gender  rank
2  richard  NaN    male   3.0
3    sarah  NaN  female   NaN
4    randy  NaN    male   NaN

In [14]:
ranking_df

      name   age  gender  rank
0    steve  20.0    male   2.0
1     john  21.0    male   1.0
2  richard   NaN    male   3.0
3    sarah   NaN  female   NaN
4    randy   NaN    male   NaN
5  micheal  38.0    male   NaN
6    julie  22.0  female   6.0

In [18]:
test = ranking_df.fillna(0)

In [24]:
test = ranking_df.bfill()
test

      name   age  gender  rank
0    steve  20.0    male   2.0
1     john  21.0    male   1.0
2  richard  38.0    male   3.0
3    sarah  38.0  female   6.0
4    randy  38.0    male   6.0
5  micheal  38.0    male   6.0
6    julie  22.0  female   6.0

In [25]:
test = ranking_df.ffill()
test

      name   age  gender  rank
0    steve  20.0    male   2.0
1     john  21.0    male   1.0
2  richard  21.0    male   3.0
3    sarah  21.0  female   3.0
4    randy  21.0    male   3.0
5  micheal  38.0    male   3.0
6    julie  22.0  female   6.0

In [30]:
ranking_df.dropna()

    name   age  gender  rank
0  steve  20.0    male   2.0
1   john  21.0    male   1.0
6  julie  22.0  female   6.0

In [31]:
ranking_df.dropna(how='all')

      name   age  gender  rank
0    steve  20.0    male   2.0
1     john  21.0    male   1.0
2  richard   NaN    male   3.0
3    sarah   NaN  female   NaN
4    randy   NaN    male   NaN
5  micheal  38.0    male   NaN
6    julie  22.0  female   6.0